name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify the Node.js version

    - name: Change directory to wellness-mate
      run: cd wellness-mate

    - name: Install dependencies
      run: npm install
      working-directory: ./wellness-mate


    - name: Run Jest
      run: npm test
      working-directory: ./wellness-mate


env:
    TEST_URL: "https://wellnessmate.vercel.app/"
      